"""Embed the CV files in a script the portal can load.

A published artifact runs in a sandboxed frame: a link with target="_blank" cannot
open a tab, and a page-initiated download is blocked outright, so neither an <a> to a
served file nor a data: URL can hand the viewer a CV. The supported route is the
`downloads` capability, which takes bytes from the page - so the bytes have to be in
the page.

This writes portal/cvdata.js, published alongside the portal as a supporting file
(JavaScript is a servable type; .docx is not, which is why the documents ride inside
the script rather than sitting next to it).

    python portal/build_cvdata.py
"""
from __future__ import annotations

import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TAILORED = ROOT / "profile" / "cv" / "tailored"
MASTER = ROOT / "profile" / "cv" / "master"
OUT = ROOT / "portal" / "cvdata.js"

WANTED = (".pdf", ".docx")


def main() -> None:
    blobs: dict[str, str] = {}
    # his own file first, so the portal hands over the master itself rather than a
    # re-render of it
    for f in sorted(MASTER.iterdir()):
        if f.suffix.lower() in WANTED:
            blobs[f.name] = base64.b64encode(f.read_bytes()).decode("ascii")
    # Only the per-job CVs whose switch is on. profile/cv/generated/ is a scratch
    # directory the builder overwrites on every run; shipping it would put stale and
    # half-built files in front of him.
    if TAILORED.is_dir():
        for f in sorted(TAILORED.iterdir()):
            if f.suffix.lower() in WANTED:
                blobs[f.name] = base64.b64encode(f.read_bytes()).decode("ascii")

    OUT.write_text(
        "// Generated by portal/build_cvdata.py - do not edit by hand.\n"
        "window.__CV_BLOBS__ = " + json.dumps(blobs) + ";\n"
    )
    total = sum(len(v) for v in blobs.values())
    print(json.dumps({
        "out": str(OUT), "files": len(blobs),
        "kb": round(OUT.stat().st_size / 1024, 1),
        "base64_chars": total,
    }, indent=2))


if __name__ == "__main__":
    main()
